### ISSUE TITLE
Reqnroll.json discovery differences between extension and reqnroll package 

### ISSUE THREAD

**Issue by jdb0123** [reqnroll/Reqnroll.VisualStudio#17]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Issue Description

The ReqnRoll package allows to place the `reqnroll.json` in other locations than the project folder.
However not all supported locations for the `reqnroll.json` in the package are valid for the visual studio extension.

The extension only seems to check the project folder.
```
private string GetReqnrollConfigFilePath(IProjectScope projectScope)
{
    var projectFolder = projectScope.ProjectFolder;
    var fileSystem = projectScope.IdeScope.FileSystem;
    return fileSystem.GetFilePathIfExists(Path.Combine(projectFolder,
               ProjectScopeDeveroomConfigurationProvider.ReqnrollJsonConfigFileName)) ??
           fileSystem.GetFilePathIfExists(Path.Combine(projectFolder,
               ProjectScopeDeveroomConfigurationProvider.SpecFlowJsonConfigFileName)) ??
           fileSystem.GetFilePathIfExists(Path.Combine(projectFolder,
               ProjectScopeDeveroomConfigurationProvider.SpecFlowAppConfigFileName));
}
```

### Steps to Reproduce

- Create a reqnroll project with feature files.
- Have a `reqnroll.json` in a parent folder of the project
```
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Content Include="..\..\..\reqnroll.json" Link="reqnroll.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```
- The reqnroll package is able to build and run the test
- The visual studio extension can't find the defined steps

**Comment by gasparnagy** [comment]
@jdb0123 I don't think this is a supported scenario currently. The fact that it works with the Reqnroll runtime is just a lucky coincidence.

What would be your proposed solution for finding the config file in the plugin?

**Comment by jdb0123** [comment]
@gasparnagy I think it should be possible to look in the project folder, if not present see if reqnroll.json (or consorts) are present in the project file. Then follow that path and use that file.

**Comment by gasparnagy** [comment]
@jdb0123 That would make sense, but unfortunately there are so many ways to "include" a file to a project (different patterns, different file includes, `Directory.Build.props`, etc.). Actually even Reqnroll loads the JSON file in a quite strange way (see [ReqnrollJsonLocator](https://github.com/reqnroll/Reqnroll/blob/main/Reqnroll/Configuration/ReqnrollJsonLocator.cs)). Maybe instead of trying to detect the file include in the project file, we should check if the file exists at the same locations where Reqnroll checks it. (That would require a compilation to copy the file, but after that it would work.) So basically the checking mechanizm that you included would need to be extended by checking the output directory (e.g. `bin/Debug/net8.0`) as well.

Do you want to try and send a PR for that?

**Comment by jdb0123** [comment]
That sounds like a plan. Will give that a shot soon.

**Comment by jdb0123** [comment]
@gasparnagy Took a bit longer than expected to start on it. Changes can be found in #31

**Comment by gasparnagy** [comment]
@jdb0123 Super, thx! I did a review on the PR.

**Comment by gasparnagy** [comment]
Fixed by #31 , I will release it tomorrow.

**Comment by gasparnagy** [comment]
@jdb0123 sorry for the delay. I try to do it today.

**Comment by gasparnagy** [comment]
It is out now: v2024.3.152
